### ISSUE TITLE
Token Auth Support?

### ISSUE THREAD

**Issue by Smuggla** [joelwking/ansible-f5#1]
****Awesome Module!

Currently uses base auth, any chance someone has worked on or added Token Support?

Thanks!

**Comment by joelwking** [comment]
Currently the modules do not use tokens, however Nathan Pearce of F5 has examples of using an [auth token](https://github.com/npearce/F5-iApps_and_Ansible-playbooks/blob/master/BIG-IP/02-README.md)
I would need to code the above logic in the module.

**Comment by TechIsCool** [comment]
I finally got permission to put this up.
https://github.com/joelwking/ansible-f5/pull/3

Have a great day.

**Comment by joelwking** [comment]
Thanks, I incorporated your changes and addressed some documentation format issues and added no_log for the password variable, which shows in ansible 2.3

**Comment by Techcadia** [comment]
@joelwking Thank you for the merge. it was a fun one to get functional. I fogot to mention that on F5 11.x if your using ldap authentication you can't auth except the local admin. but on 12.x you can auth everyone.
